"""Static SSL-pinning-removal fallback: decompile with apktool, force the app to trust system +
user CAs via a patched network_security_config.xml, rebuild, sign, reinstall.

Known limitation (documented, not hidden - see plan's "explicitly out of scope" section): this is
best-effort against obfuscated apps or apps with code-level certificate/public-key pinning (e.g. an
OkHttp CertificatePinner hardcoded in Kotlin/Java, not just a manifest-level config) - a network
security config only controls which CAs the *platform* trusts, it can't remove pinning logic baked
into the app's own code. It also only applies to a single base APK: for a split-APK (XAPK/APKM)
upload, this fallback is skipped entirely and the job fails with a clear reason, since the network
security config lives in the base APK's manifest and reassembling a patched multi-APK install isn't
implemented here.
"""

import asyncio
import re
import shutil
from pathlib import Path
from xml.etree import ElementTree as ET

from app.config import DATA_DIR, KEYSTORE_PATH

APKTOOL_BIN = "apktool"
KEYSTORE_ALIAS = "mobilept"
KEYSTORE_PASSWORD = "mobilept123"
NSC_RELATIVE_PATH = "res/xml/network_security_config.xml"

_ANDROID_NS = "http://schemas.android.com/apk/res/android"
ET.register_namespace("android", _ANDROID_NS)

_INVALID_RESOURCE_NAME_CHARS = re.compile(r"[^a-z0-9_.]")
_HIGH_API_VALUES_DIR = re.compile(r"^values-v(\d+)$")
_PRIVATE_ANDROID_COLOR_REF = re.compile(r"^@android:color/\w+$")
# Android 12 (API 31) introduced the Material You dynamic-color system. Apps compiled against API
# 31+ get per-version `values-vNN/colors.xml` entries, auto-generated by AGP/D8, that ALIAS an
# app-owned color name to a private `android:color/*` framework resource, e.g.
# `<color name="m3_sys_color_dynamic_dark_background">@android:color/bright_foreground_dark_disabled</color>`.
# This system's apktool framework (`~/.local/share/apktool/framework/1.apk`, the Debian-packaged
# android-framework-res) is older and still has those same resource IDs marked private, so aapt2
# refuses to link against them on rebuild ("resource android:color/... is private"). Confirmed
# live: a real app (targetSdkVersion 36) failed the static-patch rebuild this exact way.
#
# The fix must be surgical, not a blunt directory deletion: an earlier attempt that deleted whole
# `values-vNN/` directories also destroyed OTHER, unrelated app-owned resource definitions that
# happen to live in the same per-API directory (e.g. `m3_ref_palette_dynamic_neutral0`, a literal
# palette value with no framework reference at all) - and since apktool's `public.xml` pins the
# *original* resource ID table, a genuinely missing definition for one of those IDs fails the build
# a different way. Only the specific `@android:color/...` VALUES are the actual problem; the
# resource NAMES (and every other resource in these directories) must survive untouched. Repoint
# just those values at `@android:color/transparent` - a color resource that has been public since
# the earliest Android API levels, so it's about as safe a universally-resolvable fallback as
# exists; these are dynamic-color-system entries "themed" per Android version, not anything the
# SSL-pinning-removal patch this fallback exists for actually depends on.
_MIN_PRIVATE_RESOURCE_API = 31


class ApktoolError(RuntimeError):
    pass


def _redact_display_args(args: tuple[str, ...]) -> str:
    # Not a real secret (a fixed, documented, throwaway debug-signing password with no value
    # outside re-signing disposable test builds - see module docstring) but this string still
    # ends up in JobLogLine rows exposed via GET /api/jobs/{id}/logs on any command failure, so
    # trim it for hygiene rather than have it show up in a job's log for no reason.
    return " ".join("pass:***" if a.startswith("pass:") else a for a in args)


async def _run(*args: str, cwd: Path | None = None, timeout: int = 180) -> str:
    proc = await asyncio.create_subprocess_exec(
        *args,
        cwd=str(cwd) if cwd else None,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.STDOUT,
    )
    try:
        out, _ = await asyncio.wait_for(proc.communicate(), timeout=timeout)
    except asyncio.TimeoutError:
        proc.kill()
        raise ApktoolError(f"Command timed out: {_redact_display_args(args)}")
    text = out.decode(errors="replace")
    if proc.returncode != 0:
        raise ApktoolError(f"Command failed ({proc.returncode}): {_redact_display_args(args)}\n{text}")
    return text


def _sanitize_invalid_resource_filenames(decoded_dir: Path) -> None:
    """apktool's decompiled resource file names sometimes contain characters aapt(2) rejects on
    rebuild. The common case is a leading "$" on synthetic resources aapt2 generates when it
    extracts an inline <aapt:attr> element (e.g. a gradient embedded in a vector drawable, which is
    routine for Material "adaptive icon" foreground layers) into its own file, e.g.
    "$ic_launcher_foreground__0.xml". apktool decodes these fine, but recompiling them fails with
    "invalid entry name ... must contain only [a-z0-9_.]" - which would otherwise break the rebuild
    step for a large fraction of ordinary, real-world APKs. Rename any offending file to a
    sanitized, aapt-legal name and rewrite every textual reference to the old name (in
    res/values/public.xml and any XML that references it, e.g. via @drawable/$name) so the resource
    graph still resolves.
    """
    res_dir = decoded_dir / "res"
    if not res_dir.is_dir():
        return

    renames: dict[str, str] = {}
    for path in res_dir.rglob("*"):
        if not path.is_file():
            continue
        old_stem = path.stem
        new_stem = _INVALID_RESOURCE_NAME_CHARS.sub("_", old_stem)
        if new_stem == old_stem:
            continue
        new_path = path.with_name(f"{new_stem}{path.suffix}")
        if new_path.exists():
            raise ApktoolError(f"Cannot sanitize resource filename, collision at {new_path}")
        path.rename(new_path)
        renames[old_stem] = new_stem

    if not renames:
        return

    for xml_path in res_dir.rglob("*.xml"):
        text = xml_path.read_text(encoding="utf-8")
        patched = text
        for old_stem, new_stem in renames.items():
            patched = patched.replace(old_stem, new_stem)
        if patched != text:
            xml_path.write_text(patched, encoding="utf-8")


def _strip_private_framework_resource_overrides(decoded_dir: Path) -> None:
    """Within `res/values-vNN/` directories for NN >= _MIN_PRIVATE_RESOURCE_API (see that
    constant's comment), rewrite any element whose text is exactly `@android:color/<name>` to
    `@android:color/transparent`. Every resource NAME, and every other resource in these files, is
    left completely untouched - only the specific private-framework-reference values that fail
    rebuild are replaced.
    """
    res_dir = decoded_dir / "res"
    if not res_dir.is_dir():
        return

    for path in res_dir.iterdir():
        if not path.is_dir():
            continue
        match = _HIGH_API_VALUES_DIR.match(path.name)
        if not match or int(match.group(1)) < _MIN_PRIVATE_RESOURCE_API:
            continue
        for xml_path in path.glob("*.xml"):
            tree = ET.parse(xml_path)
            root = tree.getroot()
            changed = False
            for elem in root.iter():
                if elem.text and _PRIVATE_ANDROID_COLOR_REF.match(elem.text.strip()):
                    elem.text = "@android:color/transparent"
                    changed = True
            if changed:
                tree.write(xml_path, encoding="utf-8", xml_declaration=True)


def _write_network_security_config(decoded_dir: Path) -> None:
    nsc_path = decoded_dir / NSC_RELATIVE_PATH
    nsc_path.parent.mkdir(parents=True, exist_ok=True)
    nsc_path.write_text(
        """<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
"""
    )


def _patch_manifest(decoded_dir: Path) -> None:
    manifest_path = decoded_dir / "AndroidManifest.xml"
    tree = ET.parse(manifest_path)
    root = tree.getroot()
    application = root.find("application")
    if application is None:
        raise ApktoolError("AndroidManifest.xml has no <application> element")

    attr_key = f"{{{_ANDROID_NS}}}networkSecurityConfig"
    application.set(attr_key, "@xml/network_security_config")

    debuggable_key = f"{{{_ANDROID_NS}}}debuggable"
    application.set(debuggable_key, "true")

    tree.write(manifest_path, encoding="utf-8", xml_declaration=True)


async def patch_and_rebuild(original_apk: Path, job_id: str) -> Path:
    work_dir = DATA_DIR / "uploads" / job_id / "apktool_work"
    if work_dir.exists():
        shutil.rmtree(work_dir)
    decoded_dir = work_dir / "decoded"

    await _run(APKTOOL_BIN, "d", str(original_apk), "-o", str(decoded_dir), "-f")

    _sanitize_invalid_resource_filenames(decoded_dir)
    _strip_private_framework_resource_overrides(decoded_dir)
    _write_network_security_config(decoded_dir)
    _patch_manifest(decoded_dir)

    # This apktool package ships without a bundled aapt2 binary, so without an explicit path it
    # silently falls back to whatever `aapt` (the legacy, non-aapt2 tool) is first on $PATH. Legacy
    # aapt can't handle AAPT2-emitted private resource filenames (containing "$", e.g. flattened
    # adaptive-icon vector drawables), which are common in real, modern APKs, and the build fails.
    # Point apktool at the real aapt2 from the configured Android SDK build-tools instead.
    aapt2 = _build_tool_path("aapt2")
    unsigned_apk = work_dir / "patched-unsigned.apk"
    await _run(
        APKTOOL_BIN,
        "b",
        str(decoded_dir),
        "-o",
        str(unsigned_apk),
        "--use-aapt2",
        "-a",
        aapt2,
        timeout=300,
    )

    aligned_apk = work_dir / "patched-aligned.apk"
    zipalign = _build_tool_path("zipalign")
    await _run(zipalign, "-p", "-f", "4", str(unsigned_apk), str(aligned_apk))

    signed_apk = work_dir / "patched-signed.apk"
    apksigner = _build_tool_path("apksigner")
    await _run(
        apksigner,
        "sign",
        "--ks",
        str(KEYSTORE_PATH),
        "--ks-pass",
        f"pass:{KEYSTORE_PASSWORD}",
        "--ks-key-alias",
        KEYSTORE_ALIAS,
        "--out",
        str(signed_apk),
        str(aligned_apk),
    )
    return signed_apk


def _build_tool_path(name: str) -> str:
    import glob

    from app.config import settings

    candidates = sorted(glob.glob(f"{settings.android_home}/build-tools/*/{name}"))
    if not candidates:
        raise ApktoolError(f"{name} not found under {settings.android_home}/build-tools")
    return candidates[-1]
